spring.profiles.default: dev
spring.profiles.include: dev, API-KEY

cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key:
      secret-key: 
    s3:
      bucket-name: footprinter-media

server:
  error:
    include-stacktrace: on_param

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  datasource:
    url:
    username:
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

---

spring.config.activate.on-profile: dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/footprinter?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: team5
    password: footprinter
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

auth.jwt:
  issuer: com.swpp.footprinter
  jwtSecret: SECRET_KEY_FOR_MIGHTY_MARVELOUS_FOOTPRINTER_SERVICE
  jwtExpiration: 3600000000000

---

# To be configured when deploying to AWS
spring.config.activate.on-profile: prod
spring:
  jpa:
    hibernate:
      ddl-auto: none

---

spring.config.activate.on-profile: test

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;NON_KEYWORDS=user
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE