spring.profiles.default: dev

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

---

spring.config.activate.on-profile: dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/footprinter?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: team5
    password: footprinter
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update


---

# To be configured when deploying to AWS
spring.config.activate.on-profile: prod
spring:
  jpa:
    hibernate:
      ddl-auto: none

---

spring.config.activate.on-profile: test

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create