name: backend build

on:
  pull_request:
    paths:
      - ".github/workflows/*.yaml"
      - "backend/**"

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: grant permission to gradlew
        run: chmod +x ./gradlew

      - name: check lint & build without test
        run: ./gradlew build -x test

      - if: ${{ failure() }}
        name: print ktlint report
        run: cat ./build/reports/ktlint/**/*.txt