name: backend lint

on:
  pull_request:
    paths:
      - ".github/workflows/*.yaml"
      - "backend/**"

defaults:
  run:
    working-directory: ./backend

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: run lint
        run: |
          ./gradlew clean ktlintCheck

      - if: ${{ failure() }}
        name: print ktlint report
        run: cat ./build/reports/ktlint/**/*.txt
      
      - name: upload ktlint reports
        uses: actions/upload-artifact@v3
        with:
          name: ktlint-reports
          path: backend/build/reports/ktlint/**/*.txt
