name: backend test

on:
  pull_request:
    paths:
      - ".github/workflows/*.yaml"
      - "backend/**"

defaults:
  run:
    working-directory: ./backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: file check
        run: cd build && ls -al && cd reports && ls -al

      - name: run test with coverage
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: ./gradlew test jacocoTestReport coverallsJacoco

      - name: upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: backend/build/reports/jacoco/test/*.xml
