name: backend test

on:
  pull_request:
    paths:
      - ".github/workflows/*.yaml"
      - "backend/**"
      - "frontend/**"

defaults:
  run:
    working-directory: ./backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: run test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: ./gradlew test jacocoTestReport

      - name: run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: backend-coverage-${{ github.run_id }}
        run: ./gradlew coverallsJacoco


      - name: upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: backend/build/reports/jacoco/test/*.xml
