name: backend test

on:
  pull_request:
    paths:
      - ".github/workflows/*.yaml"
      - "backend/**"

defaults:
  run:
    working-directory: ./backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: run test with coverage
        run: ./gradlew clean test jacocoTestReport
