name: Coveralls
on:
  workflow_run:
    workflows: [frontend build, frontend test, backend lint, backend test]
    types:
      - completed

jobs:
  coveralls:
    name: Coveralls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3