name: frontend test

on:
  pull_request:
    paths:
      - ".github/workflows/*.yaml"
      - "frontend/**"

jobs:
  unittest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock

      - name: install deps
        run: yarn install

      - name: run unit tests
        run: yarn test:unit
