name: frontend test

on:
  pull_request:
    paths:
      - ".github/workflows/*.yaml"
      - "frontend/**"
      - "backend/**"

jobs:
  unittest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock

      - name: install deps
        run: yarn install

      - name: run unit tests
        run: yarn test:unit --coverage

      - name: Update lcov.info
        run: |
          cd frontend
          cat ./coverage/lcov.info
          sed -E "s/SF:(.+file:(.+))/SF:\2/g" ./coverage/lcov.info > coverage/lcov.new.info
          mv ./coverage/lcov.new.info ./coverage/lcov.info
          cat ./coverage/lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@master
        env: 
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        with:
          github-token: ${{ secrets.github_token  }}
          path-to-lcov: frontend/coverage/lcov.info

      - name: upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: frontend/coverage/lcov.info
