name: frontend test

on:
  pull_request:
    paths:
      - ".github/workflows/*.yaml"
      - "frontend/**"
      - "backend/**"

jobs:
  unittest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: checkout
        uses: actions/checkout@v3
          
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock

      - name: install deps
        run: yarn install

      - name: run unit tests
        run: yarn test:unit --coverage

      - name: Coveralls node scripts
        env: 
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: yarn coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@master
        env: 
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        with:
          github-token: ${{ secrets.github_token  }}
          path-to-lcov: frontend/coverage/lcov.info

      - name: upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: frontend/coverage/lcov.info
