name: test & coverage

on:
  pull_request:
    paths:
      - ".github/workflows/*.yaml"
      - "backend/**"
      - "frontend/**"

defaults:
  run:
    working-directory: ./backend

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: run test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: ./gradlew test jacocoTestReport

      - name: run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: backend-coverage-${{ github.run_id }}
        run: ./gradlew coverallsJacoco

  frontend-unittest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock

      - name: install deps
        run: yarn install
        working-directory: ./frontend

      - name: run unit tests
        run: yarn test:unit --coverage
        working-directory: ./frontend

      - name: Coveralls
        uses: coverallsapp/github-action@master
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        with:
          github-token: ${{ secrets.github_token  }}
          path-to-lcov: frontend/coverage/lcov.info
          base-path: frontend
          parallel: true
          flag-name: frontend-coverage-${{ github.run_id }}

  send-coverage:
    runs-on: ubuntu-latest
    name: Send Coverage Report
    needs: ['backend-test', 'frontend-unittest']
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true